name: OsteoLab
favicon: null
layout_spectrum: 0.92616
typography_spectrum: 0.13451
title: Osteo Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.058589031919837
  lightness: 0.20238536782562733
  saturation: 0.8791850828565657
  rhythmicContrast: 0.6874488755129278
purpose: []
