name: OsteoLab
favicon: null
layout_spectrum: 0.74772
typography_spectrum: 0.13451
title: Osteo Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
